### ISSUE TITLE
Support multiple tabs

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1082]

**Comment by brampitoyo** [comment]
One of our research findings was that most people use the surface layer of the browser and seldom drill down to deeper, more advanced features, and this includes tabs.

- Some people use only one tab at a time. When the information is no longer needed, the tab is closed. When it’s needed again, the URL/search term is re-inputted.
- Some people keep opening new tabs, never closing any of them.

Plus, there may also be a perception that tabs consume precious memory/disk space, that needed to be purged (like cache).

So, instead of supporting multiple tabs outright, it may be worth it to get acquainted with people’s mental models and designing a unique solution that fits it – whatever form it might take!

Some strawman starter ideas (I’m sure there are many better ones):

- One tab only. When you close this one tab and open a fresh one, the URL/search term that you have inputted last time is available as an option.
- Automatically close tabs after they’re not used for a while, then tell users how much memory they’ve saved by this automatic tidying (gives them peace of mind and assurance of maximum savings).

**Comment by Conjuror** [comment]
Good point. Per our study, some websites use pop-up page for ads and force to redirect. Users won't be able to browse these websites by single tab.

**Comment by chianger** [comment]
Currently nightly has multi-tab
