### ISSUE TITLE
Press to see a photo in FB, Rocket shows the photo in small size

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/Rocket#1212]
(Rocket, Focus)
![screenshot_20171103-181548](https://user-images.githubusercontent.com/22672569/32369240-70746c1e-c0c3-11e7-8269-6f8b3a07a343.png)
(Chrome, UC)
![screenshot_20171103-181525](https://user-images.githubusercontent.com/22672569/32369443-1eea9b2e-c0c4-11e7-88ae-ec9ff4c0bce3.png)

**Comment by chianger** [comment]
investigate whether it's because of user agent.

**Comment by mTwTm** [comment]
Confirmed useragent problem

**Comment by mTwTm** [comment]
![dsc_0002](https://user-images.githubusercontent.com/6755074/32926441-2b8ccfc8-cb82-11e7-8380-2cd72085d9f4.JPG)

**Comment by idiotmax** [comment]
Mozilla/5.0 (Linux; Android 8.0.0; **Pixel XL Build/OPR3.170623.013;** rv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Rocket/1.0.debug.maliu Chrome/62.0.3202.84 Mobile Safari/537.36

The root cause is the UserAgent string. Focus removed the "device brand and os version" as highlighted above for anonymity and we leverage code from them. As a general-purpose browser, we might have to consider the weighting among Webcompat, user experience, and TrackingProtect.

@joechengla what do you think?

**Comment by chianger** [comment]
It requires a change on the user agent so let's not do it right before the soft code freeze. 
We should have a separate build for QA to run more web compat testing in parallel.

**Comment by cynthiatang** [comment]
Verified Fixed

=========== Not Work ==============
Samsung J7
Rocket: 1.0.4 (2109) 
Android: 7.0
WebView: 64.0.3282.137
