### ISSUE TITLE
Onboarding for screenshots is missing

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/Rocket#1299]
STR

1. Launch Zerda and go to a website
2. Trigger system screenshot
3. Tap "Got it!"
4. Trigger system screenshot again

Expect Result

2. a dialog is shown to notify user screenshot capture provided by Zerda
3. dialog is dismissed
4. No dialog is shown anymore

Actual Result

2. no dialog is shown to notify user

Samsung J7 Prime
Android 6.0.1
WebView 62
Build 1803

**Comment by mTwTm** [comment]
This is the expected behavior, we need to ask for the read permission to see if any screenshot is taken but to not bother the user we're not asking the user for the permission when we start the app. We show screenshot hint after the user have granted the permission via other functions (e.g. Capture screen / Download.)

**Comment by mTwTm** [comment]
I'm a bit confused. Is this about it only show once? We also only show once no matter how an user dismiss it.

**Comment by chianger** [comment]
per discussion this is expected behavior.
