### ISSUE TITLE
Experiment: InviteReferrals

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1809]

**Comment by chianger** [comment]
Note: we'll need to update docs (e.g. telemetry wiki, ...).

**Comment by elin-moco** [comment]
Hi, this will be the referral flow (copy will be tuned by copywriter)
https://docs.google.com/document/d/1dg10Shqtl17viVLC_frqhSnIQnHq73dzpnli9Ir3l44/edit#

Here is the test link of the referral program page:
http://mozilla.ref-r.com/?campaignid=18212
After some discussion with Jack, we think it would be great if we put the referral page **in a new tab**.
So it's less intrusive and user will have more chance to get back to enroll the program after they finished their tasks.

As for the timing, we are thinking replacing the original share dialog during the campaign.
When users updated to 2.2, there will be 2 conditions:
1. the updated user have seen the share dialog, in this case, we can **prompt the referral page after 2 app launch**.
2. the updated user have not seen the share dialog, if so, after a few times of app open, we **prompt them the referral page instead of share dialog**.

**Comment by weslyhuang** [comment]
Max: should be able to start the implementation, but expect some detail about "stopping the campaign" (e.g., use a switch to turn off the experiment in Firebase? when & how?) to be further provided.

**Comment by elin-moco** [comment]
InviteReferrals documentation:
https://www.invitereferrals.com/campaign/documentation/home

**Comment by elin-moco** [comment]
We might consider go with campaign page integration, which is simplest.
Install tracking will be done via our tracking provider, which is Adjust.

Here are some info provided by InviteReferrals:
1. Please find the credentials below:

Login URL : https://www.invitereferrals.com/campaign/brand/
Username : mozilla
Password  : mozilla@789



​2. Integration requirements​
​Its almost Zero with InviteReferrals. You may link a page with your referral CTA.​
Page example: http://mozilla.ref-r.com/?campaignid=18212
​You may also create your own referral page using our iframe like THIS​

​For install tracking, We will need an api from your tracking service provider​.
No SDK integration is required.

**Comment by chianger** [comment]
Client-side validation is done and so far so good. 
As I know there's no actual code landing given Adjust SDK was in place long ago. 
Leaving the integration test to be tracked in #2056

**Comment by mTwTm** [comment]
Per what I know it's too early to close this issue. Reopening. I think #2052 is required to claim so far so good on the client side. @benjamin-cheng to confirm.

**Comment by chianger** [comment]
per discussion on slack with ben, #2052 is not hard requirement for 2.2.

**Comment by weslyhuang** [comment]
app side ready for now (until new req. input), pending on server side config.
