### ISSUE TITLE
Experiment: VPN Offering

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1820]

**Comment by weslyhuang** [comment]
Two steps here:
1. wifi finder service: need to share cost with partner so plan to design a landing page to validate the user need.
2. VPN

**Comment by weslyhuang** [comment]
need engineering study for some design input. (go with #1821's spike first)

**Comment by Jacklin-ux** [comment]
UX draft spec: https://drive.google.com/file/d/13-4IUB4DKoEi2apWJqHLTMZrsX3v7ELb/view?usp=sharing

**Comment by Pekochen** [comment]
wifi & vpn visual spec:
https://drive.google.com/open?id=1XULh6sqI2RxECra_aqvVAmUF9V9hqaiF
assets:
https://drive.google.com/open?id=1Fl0lnHb7ePeMJ1LsWvqq6UHwnICyPIfh
preview:
https://drive.google.com/open?id=1OeFAdt3wuyAYJShRtnOAfqiMUbGzLyxC

**Comment by josephyu1110** [comment]
@Pekochen Please help to grant the access permission of specs to "joseph.yu@yarboroughtech.com". Thanks!

**Comment by Pekochen** [comment]
@josephyu1110 Done : )

**Comment by josephyu1110** [comment]
@Pekochen, I can access the second link now, but still cannot access the first and the third one(wifi & vpn visual spec and preview).

**Comment by elin-moco** [comment]
@cnevinc My suggested event structure would be (in method/object/value format):
Click on VPN Button: click/home/vpn
Click "Yes" on VPN Doorhanger: click/doorhanger/positive (extra: {source: vpn})
Click "No" on VPN Doorhanger: click/doorhanger/negative (extra: {source: vpn})
Dismissed VPN Doorhanger: click/doorhanger/dismiss (extra: {source: vpn})
We'll need to put "vpn" in extra for the doorhanger so that we can compare metrics in A/B testing.
I'll separate a dashboard to visualize the extra information.
