### ISSUE TITLE
The image cannot reload immediately on Screenshot viewer

### ISSUE THREAD

**Issue by NashTung** [mozilla-tw/Rocket#1864]
STR

1. Install Rocket 2.0
2. Launch Rocket 2.0
3. Visit a website and tap on ScreenCapture icon
4. Check screenshot under Settings\My shots
5. The image cannot reload immediately on Screenshot viewer

https://drive.google.com/open?id=1sGHz9nW_f5AiybcH8-DsEJuePX1O-RZD

Expected result:

- The image reload immediately on Screenshot viewer

Actual result:

- The image cannot reload immediately on Screenshot viewer

Device: Redmi 4A
Rocket: 2.0.0(3585)
Android: 7.1.2
Webview: 65:0.3359.126

**Comment by chianger** [comment]
Can we have a video to address this issue?
Is it "thumbnail" not displaying immediately, or the picture viewer?

**Comment by NashTung** [comment]
Hi, the video is updated, and the screenshot picture cannot reload immediately on Screenshot viewer

**Comment by chianger** [comment]
Thanks @NashTung . So looks like the issue is on the speed of image loading.
If that's the case, we actually have no actionable items at this moment. 
Whenever the screenshot is fairly large, the loading takes longer. 
We added a waiting cursor to mitigate a few months ago.

Feel free to reopen the bug if you disagrees or gets more information to share.
