### ISSUE TITLE
The pop menu cannot show up after long pressing on text on any website

### ISSUE THREAD

**Issue by NashTung** [mozilla-tw/Rocket#1979]
STR

1. Install Rocket 2.0
2. Launch Rocket 2.0
3. Visit any website
4. Long pressing on text
5. The pop menu cannot show up

Video: https://drive.google.com/open?id=1UJvR1w6_vD2XlRBeY61VI2N2fE2i_lkG

Expected result:

- Pop menu can show up after long pressing on text on any website

Actual result:

- Pop menu cannot show up after long pressing on text on any website

Reproduce rate: 100%

Device: Advan i5C
Rocket: 2.1.0(4414)
Android: 5.1
Android Webview: 67.0.3369.49

**Comment by cynthiatang** [comment]
Hi @NashTung,
For Android5.x, it would show up a toolbar at the top of the screen. You can modify the test case for this issue. 

I'd like to close this issue because it works for me. Please open it again if there's something wrong. Thanks. :)

<img width="347" alt="screen shot 2018-05-23 at 5 51 04" src="https://user-images.githubusercontent.com/12458450/40417391-388c09d2-5eb2-11e8-9b23-4311da9c0550.png">

Webview: 66.0.3359.158
Rocket 2.1.0(4414)
Device: Oppo A37f
Android: 5.1.1
