### ISSUE TITLE
 No any message to notify the file saved to internal storage when SD card is almost full

### ISSUE THREAD

**Issue by NashTung** [mozilla-tw/Rocket#1984]
STR

1. Install Rocket 2.0
2. Check the capacity is almost full on SD card
3. Check the capacity is enough on internal storage 
3. Launch Rocket 2.0
4. Download the file on any website
5. No any message to notify the file saved to internal storage

Video: https://drive.google.com/open?id=1Vv3V4zwbt8pHccantyhjqMZHpHT-NPTr

Expected result:

- It must be some message notify user the storage is changed

Actual result:

- No any message to notify user the storage is changed

Reproduce rate: 100%

Device: Advan i5C
Rocket: 2.1.0(4414)
Android: 5.1
Android Webview: 67.0.3369.49

**Comment by cynthiatang** [comment]
Hi @NashTung ,  

I would like to close this issue. Because there is a banner. It shows "SD card is almost full. File was saved to internal storage" (your video: 7:17)

here is the original test case. 

Prerequisite: Device external storage is almost full
1. Launch Zerda
2. Visit a page with files to download
3. Attempt to download a file with its size over available storage

Expected result: 
 - A file is saved to internal storage with a banner to notify the user

Actual result: 
 - A file is saved to internal storage with a banner to notify the user
 - Your video (7:17): There is a banner. It shows "SD card is almost full. File was saved to internal storage"

<img width="1183" alt="screen shot 2018-05-24 at 11 26 37" src="https://user-images.githubusercontent.com/12458450/40463149-12d13d22-5f46-11e8-9a29-275677f92d00.png">
