### ISSUE TITLE
Telemetry: Understand screenshot better

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/Rocket#1987]
Without knowing the site URL, can we categorize and annonymize the types of website screenshots were taken on? Is it mostly shopping? News?... Etc

**Comment by weslyhuang** [comment]
Joe will put more detail req. about this one.

**Comment by weslyhuang** [comment]
question from Joe: is it feasible to update the list via firebase?

**Comment by joechengla** [comment]
We will want to update the conversion whitelist remotely as well

**Comment by weslyhuang** [comment]
1. Joe to classify the list (top100)
2. Nevin to study the feasibility (list updating via firebase)

**Comment by joechengla** [comment]
need PN update https://github.com/mozilla-tw/Rocket/issues/2037

**Comment by joechengla** [comment]
this could probably be done with Pocket backend as well

**Comment by joechengla** [comment]
related https://github.com/mozilla-tw/Rocket/issues/2066

**Comment by weslyhuang** [comment]
Joe is discussing with Pocket if there can be a leverage of their back-end tech.

**Comment by chianger** [comment]
potentially a dot release (2.4.1) feature.

**Comment by joechengla** [comment]
Let's Add category in Screenshot INFO as well so user know how their screenshot is categorized

**Comment by chianger** [comment]
categorization mapping table  (permission required)
https://docs.google.com/spreadsheets/d/1GzYQyKlUa_MT94L8cEgjstY33lZeaHUiA1LWXsYOW50/edit#gid=910797273

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/1paKUoAmoYGcVIlGKhC3B__isS8VZEKya/view?usp=sharing

**Comment by Pekochen** [comment]
Hi, Updated screenshot onboarding visual spec
please check here
https://drive.google.com/open?id=1VnpJXZmrxGFsH7iotK1VsR0oRrxqsB9E
if you have any question please let me know, Thank you.

**Comment by chianger** [comment]
the "learn more" page goes to https://bugzilla.mozilla.org/show_bug.cgi?id=1483506 which is not done yet. I'm asking if we can at least get the URL beforehand.

**Comment by cnevinc** [comment]
@joechengla 
Please advise what UI events we should collect

- [ ] The user clicks "Learn More"
- [ ] The user dismisses the on-boarding using the back key
- [ ] The user dismisses the on-boarding by clicking the other area.

**Comment by cnevinc** [comment]
@joechengla. I've prepared a sample for the data review request form. Could you please modify to fit your needs? Thank you!

1. What questions will you answer with this data?
We want to know what kind of webpage users like to take screenshots on.

2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:
Product team needs more information from the user.

3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
We don't have any information related to the webpage category.

4. Can current instrumentation answer these questions?
No.

5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories on the Mozilla wiki.
Category 3 (categories of webpages visited over time) But since we don't have any user identity saved. It should be treated as anonymous. 

6. How long will this data be collected? Choose one of the following:
Product team want to collect this data as long as possible.

7. What populations will you measure?
All users in all channels.

8. If this data collection is default on, what is the opt-out mechanism for users?
The user can disable "Send usage data" in settings to opt-out.

9. Please provide a general description of how you will analyze this data.
We'll use Firebase and STMO.  Comparing retention rate and the screenshot usage over time.

10. Where do you intend to share the results of your analysis?
No
