### ISSUE TITLE
When visiting different websites and tap menu - history, only after accepting cookie policy will the website appear on history list.

### ISSUE THREAD

**Issue by mlwang32** [mozilla-tw/Rocket#2461]
Prerequisite:
User has not accepted cookie from CNN.com

STR:

1. Launch Rocket
2. Visit cnn.com
3. Tap menu
4. Tap history
5. Accept cookie policy
6. Tap history under menu again

Expected result:
Visited website should appear on history list

Actual result:
CNN.com appears on history list only after user accepts cookie policy

Reproduce Rate: 100%

Device: Samsung Galaxy J7 Prime
Rocket Ver.: 3.0.0(6354)
Android Ver.: 7.0
WebView: 68.0.3440.91

Clip;
https://drive.google.com/open?id=1vso8NBt_gLVGQES3Xb-bksVBSKmChVHh

**Comment by cynthiatang** [comment]
@mlwang32 
I would like to close this issue. Because it works for me.

STR:
 - Launch Rocket
 - Visit cnn.com
 - Wait for the window "cookie policy"
 - Tap history under menu again
Actual result: 
 - The visited website should appear on the history list
 - https://drive.google.com/open?id=1dXqWQ1CUKPCmMXYsF7PTl0KtCBO43R-h
