### ISSUE TITLE
Refresh is only on error pages rather than the page if pages fails before loaded

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/Rocket#907]
STR:

1. Turn off network
2. Load any page
3. One should receive the error page
4. Turn on network and refresh
5. One is still seeing the error page (Expected: the page should be loaded.)

Comparison:
If in step 4 "Try again" button is clicked, page will load successfully
If we first load successfully before step 1, then refresh in step 2, page will load successfully in step 5.

**Comment by mTwTm** [comment]
Same behavior on Focus

**Comment by hartsu** [comment]
We found that if error page is the first page been loaded, `WebView.getOriginalUrl()` would be "data:text/html;charset=utf-8;base64,".
And the consequent `WebView.reload()` would load the error page instead of the actual page.
Therefore, the workaround for this is specifically load the actual page while `WebView.getOriginalUrl()` is equal to internal error URL.

**Comment by walkingice** [comment]
Looks like we need more work on fixing this issue. It won't reload in below situation

1. Launch Rocket with connected network
1. Open any web page, and it would load correctly
1. turn off WiFi, reload -> now we got error page
1. turn on WiFi, reload -> got white screen
1. reload again -> even URL becomes internal-error-url
